#!/usr/bin/env bash

pacman -S git --noconfirm

git config --global user.email "daniele.pintore1@gmail.com"
git config --global user.name "Daniele Pintore"
git config --global init.defaultbranch main
git config --global core.editor nvim
