#!/usr/bin/env bash

# system utils
yay -S noctalia-shell xwaylandvideobridge btrfs-assistant

# nautilus open any terminal with wezterm
yay -S nautilus-open-any-terminal
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal wezterm

# user packages
yay -S android-apktool anytype-bin burpsuite cura-bin dex2jar ente-auth-bin \
	httpie-desktop-bin jdownloader2 lrcget-bin qdirstat teams-for-linux termius \
	vdhcoapp-bin wezterm-nightly-bin
