#!/usr/bin/env bash

# system utils
yay -S xwaylandvideobridge btrfs-assistant waypaper

# user packages
yay -S android-apktool anytype-bin burpsuite cura-bin dex2jar ente-auth-bin \
	httpie-desktop-bin jdownloader2 lrcget-bin qdirstat teams-for-linux termius \
	vdhcoapp-bin wezterm-nightly-bin
